//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceProblemsInitParameters) DeepCopyInto(out *ComplianceProblemsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceProblemsInitParameters.
func (in *ComplianceProblemsInitParameters) DeepCopy() *ComplianceProblemsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ComplianceProblemsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceProblemsObservation) DeepCopyInto(out *ComplianceProblemsObservation) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceProblemsObservation.
func (in *ComplianceProblemsObservation) DeepCopy() *ComplianceProblemsObservation {
	if in == nil {
		return nil
	}
	out := new(ComplianceProblemsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceProblemsParameters) DeepCopyInto(out *ComplianceProblemsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceProblemsParameters.
func (in *ComplianceProblemsParameters) DeepCopy() *ComplianceProblemsParameters {
	if in == nil {
		return nil
	}
	out := new(ComplianceProblemsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoginV2InitParameters) DeepCopyInto(out *LoginV2InitParameters) {
	*out = *in
	if in.BaseURI != nil {
		in, out := &in.BaseURI, &out.BaseURI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoginV2InitParameters.
func (in *LoginV2InitParameters) DeepCopy() *LoginV2InitParameters {
	if in == nil {
		return nil
	}
	out := new(LoginV2InitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoginV2Observation) DeepCopyInto(out *LoginV2Observation) {
	*out = *in
	if in.BaseURI != nil {
		in, out := &in.BaseURI, &out.BaseURI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoginV2Observation.
func (in *LoginV2Observation) DeepCopy() *LoginV2Observation {
	if in == nil {
		return nil
	}
	out := new(LoginV2Observation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoginV2Parameters) DeepCopyInto(out *LoginV2Parameters) {
	*out = *in
	if in.BaseURI != nil {
		in, out := &in.BaseURI, &out.BaseURI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoginV2Parameters.
func (in *LoginV2Parameters) DeepCopy() *LoginV2Parameters {
	if in == nil {
		return nil
	}
	out := new(LoginV2Parameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoginVersionInitParameters) DeepCopyInto(out *LoginVersionInitParameters) {
	*out = *in
	if in.LoginV1 != nil {
		in, out := &in.LoginV1, &out.LoginV1
		*out = new(bool)
		**out = **in
	}
	if in.LoginV2 != nil {
		in, out := &in.LoginV2, &out.LoginV2
		*out = make([]LoginV2InitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoginVersionInitParameters.
func (in *LoginVersionInitParameters) DeepCopy() *LoginVersionInitParameters {
	if in == nil {
		return nil
	}
	out := new(LoginVersionInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoginVersionObservation) DeepCopyInto(out *LoginVersionObservation) {
	*out = *in
	if in.LoginV1 != nil {
		in, out := &in.LoginV1, &out.LoginV1
		*out = new(bool)
		**out = **in
	}
	if in.LoginV2 != nil {
		in, out := &in.LoginV2, &out.LoginV2
		*out = make([]LoginV2Observation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoginVersionObservation.
func (in *LoginVersionObservation) DeepCopy() *LoginVersionObservation {
	if in == nil {
		return nil
	}
	out := new(LoginVersionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoginVersionParameters) DeepCopyInto(out *LoginVersionParameters) {
	*out = *in
	if in.LoginV1 != nil {
		in, out := &in.LoginV1, &out.LoginV1
		*out = new(bool)
		**out = **in
	}
	if in.LoginV2 != nil {
		in, out := &in.LoginV2, &out.LoginV2
		*out = make([]LoginV2Parameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoginVersionParameters.
func (in *LoginVersionParameters) DeepCopy() *LoginVersionParameters {
	if in == nil {
		return nil
	}
	out := new(LoginVersionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Oidc) DeepCopyInto(out *Oidc) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Oidc.
func (in *Oidc) DeepCopy() *Oidc {
	if in == nil {
		return nil
	}
	out := new(Oidc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Oidc) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OidcInitParameters) DeepCopyInto(out *OidcInitParameters) {
	*out = *in
	if in.AccessTokenRoleAssertion != nil {
		in, out := &in.AccessTokenRoleAssertion, &out.AccessTokenRoleAssertion
		*out = new(bool)
		**out = **in
	}
	if in.AccessTokenType != nil {
		in, out := &in.AccessTokenType, &out.AccessTokenType
		*out = new(string)
		**out = **in
	}
	if in.AdditionalOrigins != nil {
		in, out := &in.AdditionalOrigins, &out.AdditionalOrigins
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AppType != nil {
		in, out := &in.AppType, &out.AppType
		*out = new(string)
		**out = **in
	}
	if in.AuthMethodType != nil {
		in, out := &in.AuthMethodType, &out.AuthMethodType
		*out = new(string)
		**out = **in
	}
	if in.BackChannelLogoutURI != nil {
		in, out := &in.BackChannelLogoutURI, &out.BackChannelLogoutURI
		*out = new(string)
		**out = **in
	}
	if in.ClockSkew != nil {
		in, out := &in.ClockSkew, &out.ClockSkew
		*out = new(string)
		**out = **in
	}
	if in.DevMode != nil {
		in, out := &in.DevMode, &out.DevMode
		*out = new(bool)
		**out = **in
	}
	if in.GrantTypes != nil {
		in, out := &in.GrantTypes, &out.GrantTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IDTokenRoleAssertion != nil {
		in, out := &in.IDTokenRoleAssertion, &out.IDTokenRoleAssertion
		*out = new(bool)
		**out = **in
	}
	if in.IDTokenUserinfoAssertion != nil {
		in, out := &in.IDTokenUserinfoAssertion, &out.IDTokenUserinfoAssertion
		*out = new(bool)
		**out = **in
	}
	if in.LoginVersion != nil {
		in, out := &in.LoginVersion, &out.LoginVersion
		*out = make([]LoginVersionInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.OrgIDRef != nil {
		in, out := &in.OrgIDRef, &out.OrgIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrgIDSelector != nil {
		in, out := &in.OrgIDSelector, &out.OrgIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.PostLogoutRedirectUris != nil {
		in, out := &in.PostLogoutRedirectUris, &out.PostLogoutRedirectUris
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.ProjectIDRef != nil {
		in, out := &in.ProjectIDRef, &out.ProjectIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectIDSelector != nil {
		in, out := &in.ProjectIDSelector, &out.ProjectIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.RedirectUris != nil {
		in, out := &in.RedirectUris, &out.RedirectUris
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ResponseTypes != nil {
		in, out := &in.ResponseTypes, &out.ResponseTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SkipNativeAppSuccessPage != nil {
		in, out := &in.SkipNativeAppSuccessPage, &out.SkipNativeAppSuccessPage
		*out = new(bool)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OidcInitParameters.
func (in *OidcInitParameters) DeepCopy() *OidcInitParameters {
	if in == nil {
		return nil
	}
	out := new(OidcInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OidcList) DeepCopyInto(out *OidcList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Oidc, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OidcList.
func (in *OidcList) DeepCopy() *OidcList {
	if in == nil {
		return nil
	}
	out := new(OidcList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OidcList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OidcObservation) DeepCopyInto(out *OidcObservation) {
	*out = *in
	if in.AccessTokenRoleAssertion != nil {
		in, out := &in.AccessTokenRoleAssertion, &out.AccessTokenRoleAssertion
		*out = new(bool)
		**out = **in
	}
	if in.AccessTokenType != nil {
		in, out := &in.AccessTokenType, &out.AccessTokenType
		*out = new(string)
		**out = **in
	}
	if in.AdditionalOrigins != nil {
		in, out := &in.AdditionalOrigins, &out.AdditionalOrigins
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AppType != nil {
		in, out := &in.AppType, &out.AppType
		*out = new(string)
		**out = **in
	}
	if in.AuthMethodType != nil {
		in, out := &in.AuthMethodType, &out.AuthMethodType
		*out = new(string)
		**out = **in
	}
	if in.BackChannelLogoutURI != nil {
		in, out := &in.BackChannelLogoutURI, &out.BackChannelLogoutURI
		*out = new(string)
		**out = **in
	}
	if in.ClockSkew != nil {
		in, out := &in.ClockSkew, &out.ClockSkew
		*out = new(string)
		**out = **in
	}
	if in.ComplianceProblems != nil {
		in, out := &in.ComplianceProblems, &out.ComplianceProblems
		*out = make([]ComplianceProblemsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DevMode != nil {
		in, out := &in.DevMode, &out.DevMode
		*out = new(bool)
		**out = **in
	}
	if in.GrantTypes != nil {
		in, out := &in.GrantTypes, &out.GrantTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IDTokenRoleAssertion != nil {
		in, out := &in.IDTokenRoleAssertion, &out.IDTokenRoleAssertion
		*out = new(bool)
		**out = **in
	}
	if in.IDTokenUserinfoAssertion != nil {
		in, out := &in.IDTokenUserinfoAssertion, &out.IDTokenUserinfoAssertion
		*out = new(bool)
		**out = **in
	}
	if in.LoginVersion != nil {
		in, out := &in.LoginVersion, &out.LoginVersion
		*out = make([]LoginVersionObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NoneCompliant != nil {
		in, out := &in.NoneCompliant, &out.NoneCompliant
		*out = new(bool)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.PostLogoutRedirectUris != nil {
		in, out := &in.PostLogoutRedirectUris, &out.PostLogoutRedirectUris
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.RedirectUris != nil {
		in, out := &in.RedirectUris, &out.RedirectUris
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ResponseTypes != nil {
		in, out := &in.ResponseTypes, &out.ResponseTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SkipNativeAppSuccessPage != nil {
		in, out := &in.SkipNativeAppSuccessPage, &out.SkipNativeAppSuccessPage
		*out = new(bool)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OidcObservation.
func (in *OidcObservation) DeepCopy() *OidcObservation {
	if in == nil {
		return nil
	}
	out := new(OidcObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OidcParameters) DeepCopyInto(out *OidcParameters) {
	*out = *in
	if in.AccessTokenRoleAssertion != nil {
		in, out := &in.AccessTokenRoleAssertion, &out.AccessTokenRoleAssertion
		*out = new(bool)
		**out = **in
	}
	if in.AccessTokenType != nil {
		in, out := &in.AccessTokenType, &out.AccessTokenType
		*out = new(string)
		**out = **in
	}
	if in.AdditionalOrigins != nil {
		in, out := &in.AdditionalOrigins, &out.AdditionalOrigins
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AppType != nil {
		in, out := &in.AppType, &out.AppType
		*out = new(string)
		**out = **in
	}
	if in.AuthMethodType != nil {
		in, out := &in.AuthMethodType, &out.AuthMethodType
		*out = new(string)
		**out = **in
	}
	if in.BackChannelLogoutURI != nil {
		in, out := &in.BackChannelLogoutURI, &out.BackChannelLogoutURI
		*out = new(string)
		**out = **in
	}
	if in.ClockSkew != nil {
		in, out := &in.ClockSkew, &out.ClockSkew
		*out = new(string)
		**out = **in
	}
	if in.DevMode != nil {
		in, out := &in.DevMode, &out.DevMode
		*out = new(bool)
		**out = **in
	}
	if in.GrantTypes != nil {
		in, out := &in.GrantTypes, &out.GrantTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IDTokenRoleAssertion != nil {
		in, out := &in.IDTokenRoleAssertion, &out.IDTokenRoleAssertion
		*out = new(bool)
		**out = **in
	}
	if in.IDTokenUserinfoAssertion != nil {
		in, out := &in.IDTokenUserinfoAssertion, &out.IDTokenUserinfoAssertion
		*out = new(bool)
		**out = **in
	}
	if in.LoginVersion != nil {
		in, out := &in.LoginVersion, &out.LoginVersion
		*out = make([]LoginVersionParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.OrgIDRef != nil {
		in, out := &in.OrgIDRef, &out.OrgIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrgIDSelector != nil {
		in, out := &in.OrgIDSelector, &out.OrgIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.PostLogoutRedirectUris != nil {
		in, out := &in.PostLogoutRedirectUris, &out.PostLogoutRedirectUris
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.ProjectIDRef != nil {
		in, out := &in.ProjectIDRef, &out.ProjectIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectIDSelector != nil {
		in, out := &in.ProjectIDSelector, &out.ProjectIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.RedirectUris != nil {
		in, out := &in.RedirectUris, &out.RedirectUris
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ResponseTypes != nil {
		in, out := &in.ResponseTypes, &out.ResponseTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SkipNativeAppSuccessPage != nil {
		in, out := &in.SkipNativeAppSuccessPage, &out.SkipNativeAppSuccessPage
		*out = new(bool)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OidcParameters.
func (in *OidcParameters) DeepCopy() *OidcParameters {
	if in == nil {
		return nil
	}
	out := new(OidcParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OidcSpec) DeepCopyInto(out *OidcSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OidcSpec.
func (in *OidcSpec) DeepCopy() *OidcSpec {
	if in == nil {
		return nil
	}
	out := new(OidcSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OidcStatus) DeepCopyInto(out *OidcStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OidcStatus.
func (in *OidcStatus) DeepCopy() *OidcStatus {
	if in == nil {
		return nil
	}
	out := new(OidcStatus)
	in.DeepCopyInto(out)
	return out
}
